name: FREE WARP

on:
  push:
    branches: [ "main" ]
    paths:
      - 'main.py'
  schedule: #every fuckin 60 minutes
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python main.py
    - name: Commit and push changes
      run: |          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config credential.helper store
          git add -A
          git commit -m "Last Run - $(TZ='Asia/Yangon' date '+%Y-%m-%d %H:%M:%S')"
          git push
